### ISSUE TITLE
Intron quantification with UMI?

### ISSUE THREAD

**Issue by cnk113** [songlab-cal/scquint#1]
Hello,

I was reading the preprint and I noticed this was mainly on SS2, would the intron quantification step work at UMI resolution? 

Best,
Chang

**Comment by gonzalobenegas** [comment]
Hello,

We've tried running on 10x UMI data but very few alternative introns were detected. For UMI data I would recommend other methods such as Sierra:

Patrick, Ralph, et al. "Sierra: discovery of differential transcript usage from polyA-captured single-cell RNA-seq data." Genome biology 21.1 (2020): 1-27.

Best,
Gonzalo
