### ISSUE TITLE
WARNING: optimization failed, too many tries

### ISSUE THREAD

**Issue by jnotwell** [songlab-cal/scquint#2]
Hello,

I am trying to replicate the differential splicing comparison between Glutamatergic and GABAergic neurons from your beautiful paper.

I downloaded the spliced AnnData object from [figshare](https://figshare.com/articles/dataset/scQuint_data_objects_-_Mouse_primary_motor_cortex_BICCN_/14471754) and installed the software in a new VM (Ubuntu 20.04.4 LTS; Python 3.8.10). Next, I followed the instructions from [`differential_splicing_example.ipynb`](https://github.com/songlab-cal/scquint/blob/main/differential_splicing_example.ipynb) with small modifications:

```
import anndata
import numpy as np

from scquint.differential_splicing import run_differential_splicing

adata = anndata.read_h5ad('adata_spl.h5ad')

cell_idx_a = np.where(adata.obs['class_label'] == 'GABAergic')[0]
cell_idx_b = np.where(adata.obs['class_label'] == 'Glutamatergic')[0]

clusters, introns = run_differential_splicing(adata, cell_idx_a, cell_idx_b, min_cells_per_cluster=50, min_total_cells_per_intron=50, n_jobs=5)
```

While running, I got the following warning:

```
WARNING: optimization failed, too many tries
```

When I inspect the `clusters` DataFrame, I see the following:

```
         p_value  ll_null   ll  n_classes             gene_id  max_abs_delta_psi  max_abs_lfc_psi  ranking  p_value_adj
cluster                                                                                                                
0            1.0     -inf -inf          2  ENSMUSG00000033845           0.007565         1.456648        0          1.0
9137         1.0     -inf -inf          4  ENSMUSG00000075704           0.134621         4.476370        1          1.0
9138         1.0     -inf -inf          2  ENSMUSG00000075704           0.009064         1.423936        2          1.0
9139         1.0     -inf -inf          2  ENSMUSG00000075704           0.033369         1.638647        3          1.0
9140         1.0     -inf -inf          2  ENSMUSG00000005262           0.183419         0.793877        4          1.0
```

Any advice? At this point, I have tried stepping through the code and running it on count matrices for other data - I keep running into the same issue.

Thanks,
Jim

**Comment by gonzalobenegas** [comment]
Hi Jim,

Thanks for opening the issue. I've just pushed some updates I had forgotten about, I'm sorry. Could you try again and let me know how it goes?

After the updates, I've been able to run the differential splicing test between those two groups satisfactorily in our server. With 32 cores it took a few seconds. I've also created a [Colab notebook](https://colab.research.google.com/drive/1IY86Ya4VgpjBe_VP3-YegP5l9WqHEI9V?usp=sharing) where I could run it satisfactorily (with a reduced dataset since it's only 1 core).

Best,
Gonzalo

**Comment by jnotwell** [comment]
Hi Gonzalo,

Works like a charm - thanks for the fast response!

And congratulations on the paper - it was a fun read.

Thanks again,
Jim

**Comment by gonzalobenegas** [comment]
Thanks, I'm very glad you enjoyed reading our paper!
