### ISSUE TITLE
Cannot install scquint

### ISSUE THREAD

**Issue by igunduz** [songlab-cal/scquint#3]
Hi,
I tried to install `scquint `through 

`pip install git+https://github.com/songlab-cal/scquint.git` and also `pip install "scquint[vae] @ git+https://github.com/songlab-cal/scquint.git"` 

However, installation failed due to 

> error: package directory 'scquint/quantification' does not exist

Can you help me to install it, please?
Kind regards,
İrem

**Comment by gonzalobenegas** [comment]
Hi İrem,
You should be able to install now with the latest version just pushed. Sorry about that. Let me know if you are still having issues.
Best,
Gonzalo

**Comment by igunduz** [comment]
Hello again,
Now I installed it, thank you!

Kind regards,
İrem
