### ISSUE TITLE
About np.delete in pca.py

### ISSUE THREAD

**Issue by zhenxingjian** [songlab-cal/scquint#5]
Hi,

I read the code and saw that in the pca.py file, you delete the first indices, which I would assume the first time that each intron group appears. 
May I ask why? 
In my understanding, we should gather each intron that first appears?

Thanks.

**Comment by gonzalobenegas** [comment]
Hi! Since the PSI of all the n introns in a group adds to 1, the actual dimensionality is n-1, so you can discard any intron and  keep the same information. We remove the first one for simplicity. Does it make sense?

**Comment by zhenxingjian** [comment]
Yeah, that makes sense.
Any possibility that the intron in the group is unique that n=1?
Or do you filter it out such that n>=2?

**Comment by gonzalobenegas** [comment]
They are filtered out (unless there's a bug :) ).
