### ISSUE TITLE
WARNING: optimization failed for intron_group 

### ISSUE THREAD

**Issue by TolgaDuz** [songlab-cal/scquint#7]
Hi Gonzalo,

thanks for this wonderful tool.
I am encountering a weird Issue, that I couldn't solve (see below). Do you know how to solve it?

![Screenshot 2023-08-04 at 09 53 06](https://github.com/songlab-cal/scquint/assets/91309592/e695564c-e00e-4d35-80f0-d16573ea5699)

Best,
Tolga

**Comment by gonzalobenegas** [comment]
Hi Tolga,

I'm not sure what it could be yet. Could you print the counts at that specific intron group? The total counts per group would also help. Do you notice anything unusual?

Feel free to upload the anndata file if it's easier. 

Best,
Gonzalo

**Comment by TolgaDuz** [comment]
Hi Gonzalo,

sure, here is my adata file! 

[adata.h5ad.zip](https://github.com/songlab-cal/scquint/files/12266324/adata.h5ad.zip)

Thanks!

Best,
Tolga

**Comment by gonzalobenegas** [comment]
Hi Tolga,

An intron in this intron group is only observed in 10 cells, below the minimum number of cells we recommend (30).  I've updated the thresholds in the latest commit (https://github.com/songlab-cal/scquint/commit/f356b4aff1263f65ad35c5425dd635e61ae0a785). After setting this threshold, this intron group would not be tested.

Best,
Gonzalo
